kind: pipeline
name: default

steps:
- name: install
  image: node:12
  commands:
    - cd data-cube-manager
    - npm install

- name: build-test
  image: node:12
  commands:
    - cd data-cube-manager
    - npm run build

- name: build
  image: node:12
  commands:
    - cd data-cube-manager
    - npm run build -- --prod --base-href /dev/dc-manager/ --deploy-url /dev/dc-manager/
  when:
    event:
      - tag
      - push

- name: docker-registry
  image: plugins/docker
  network_mode: bridge
  settings:
    auto_tag: true
    custom_dns: 150.163.2.4
    repo: registry.dpi.inpe.br/brazildatacube/data-cube-manager
    registry: registry.dpi.inpe.br
    username:
      from_secret: registry_user
    password:
      from_secret: registry_pass
    dockerfile: deploy/Dockerfile
