kind: pipeline
name: default

steps:
- name: install
  image: node:12
  commands:
    - cd data-cube-manager
    - npm install

- name: build-test
  image: node:12
  commands:
    - cd data-cube-manager
    - npm run build

- name: build
  image: node:12
  commands:
    - cd data-cube-manager
    - npm run build -- --prod --base-href /dev/dc-manager/ --deploy-url /dev/dc-manager/
  when:
    event:
      - tag

- name: docker-registry
  image: plugins/docker
  network_mode: bridge
  settings:
    repo: registry.dpi.inpe.br/brazildatacube/data-cube-manager
    registry: registry.dpi.inpe.br
    insecure: true
    username:
      from_secret: registry_user
    password:
      from_secret: registry_pass
    tags:
      - latest
      - ${DRONE_SEMVER}
    dockerfile: deploy/Dockerfile
  when:
    event:
      - tag